{{- $fullName := include "pvc-exporter.fullname" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}-block-pvc-scanner
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullName }}
    com: {{ $fullName }}-block-pvc-scanner
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}
      com: {{ $fullName }}-block-pvc-scanner
  template:
    metadata:
      labels:
        app: {{ $fullName }}
        com: {{ $fullName }}-block-pvc-scanner
    spec:
      imagePullSecrets:
        {{- toYaml .Values.BlockPvcScanner.image.pullSecrets | nindent 8 }}
      {{- with .Values.BlockPvcScanner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.BlockPvcScanner.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: block-pvc-scanner
        {{- with .Values.BlockPvcScanner.image }}
        image: "{{ .repository }}{{ if .digest }}@{{ .digest }}{{ else }}:{{ .tag }}{{ end }}"
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        ports:
        - containerPort: {{.Values.BlockPvcScanner.containerPort}}
          name: metrics
          protocol: TCP
        resources:
          {{- toYaml .Values.BlockPvcScanner.resources | nindent 12 }}
        volumeMounts:
        - name: root-path
          mountPath: /host
          readOnly: true
        livenessProbe:
          {{- toYaml .Values.BlockPvcScanner.livenessProbe | nindent 12 }}
        securityContext:
          {{- toYaml .Values.BlockPvcScanner.securityContext | nindent 12 }}
      volumes:
      - name: root-path
        hostPath:
          path: /
