{{- $fullName := include "pvc-exporter.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $fullName }}
    com: {{ $fullName }}-block-pvc-scanner
    {{- with .Values.BlockPvcScanner.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.BlockPvcScanner.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}-block-pvc-scanner
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - port: {{.Values.BlockPvcScanner.service.port}}
    name: metrics
    protocol: TCP
    targetPort: {{.Values.BlockPvcScanner.containerPort}}
  selector:
    app: {{ $fullName }}
    com: {{ $fullName }}-block-pvc-scanner
  {{- if .Values.BlockPvcScanner.service.headless }}
  clusterIP: None
  {{- else }}
  type: {{.Values.BlockPvcScanner.service.type }}
  {{- end }}
